version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install devtools
          command: |
            rustup install nightly
            rustup component add --toolchain nightly rustfmt
      - run:
          name: Version information
          command: |
            rustc +nightly --version --verbose
            cargo +nightly --version --verbose
            rustfmt +nightly --version --verbose
      - run:
          name: Run rustfmt
          command: cargo +nightly fmt --all -- --check
      - run:
          name: Build
          command: cargo +nightly build
      - run:
          name: Run tests
          command: cargo +nightly test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"