[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
description = "A low-level, cycle-accurate Game Boy emulation library"
edition = "2018"
name = "gib-core"
version = "0.5.2"

[dependencies]
bitflags = "2.11.0"
crossbeam = "0.8.4"
thiserror = "2.0.18"
tracing = "0.1.44"
