[package]
name = "gib-core"
version = "0.4.3"
description = "A low-level, cycle-accurate Game Boy emulation library"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
bitflags = "1.0.4"
